package com.company;

import java.text.DecimalFormat;
import java.util.HashSet;

public class Vertex {
    double xCoord;
    double yCoord;
    boolean village = false;
    boolean city = false;
    Vertex next = null;
    int num;
    int idPlayer = -1;
    HashSet<Integer> HexNum = new HashSet<>(3);
    /*copy constructor*/
    public Vertex(Vertex v){
        xCoord=v.xCoord;
        yCoord=v.yCoord;
        HexNum=v.HexNum;
        num=v.num;
        city=v.city;
        village=v.village;
        next=null;
    }
    /*constructor*/
    public Vertex(double x,double y,int N){
        xCoord=x;
        yCoord=y;
        HexNum.add(N);
        num=-1;

    }
    /*to compare if the two Vertex are the same(on the same place)*/
    public boolean equal(Vertex vertex){
        DecimalFormat df = new DecimalFormat("0.00");
        String s1 = df.format(xCoord );
        String s2 = df.format(vertex.xCoord );
        String s3 = df.format(yCoord );
        String s4 = df.format(vertex.yCoord );
        /*to avoid error generated by calculating coordinates in doubles in comparison*/
        if(s1.equals(s2)  && s3.equals(s4))
            return true;
        else
            return false;
    }
    /*interface allows adding new hex info to the existing Vertex*/
    public void adds(int N){
        HexNum.add(N);
    }

}
